<div class="table-of-contents">
    <h4>فهرست</h4>
    <ul class="list-plain">
        <li><a href="/">مقدمه</a></li>
        <li><a href="<?= page_path('installing-php') ?>">نصب پی اچ پی</a></li>
    </ul>
    <ol dir="rtl">
        <li><a href="<?= page_path('basics') ?>">اصول پایه</a></li>
        <li><a href="<?= page_path('variables') ?>">متغیر ها</a></li>
        <li><a href="<?= page_path('arithmetic') ?>">حسابگر ها</a></li>
        <li><a href="<?= page_path('strings') ?>">رشته ها</a></li>
        <li><a href="<?= page_path('comparisons') ?>">عملگرهای مقایسه ای</a></li>
        <li><a href="<?= page_path('boolean-logic') ?>">عملگرهای منطقی</a></li>
        <li><a href="<?= page_path('conditionals') ?>">شرط ها</a></li>
        <li><a href="<?= page_path('loops') ?>">حلقه ها</a></li>
        <li><a href="<?= page_path('arrays') ?>">آرایه ها</a></li>
        <li><a href="<?= page_path('functions') ?>">توابع</a></li>
        <li><a href="<?= page_path('classes') ?>">کلاس ها</a></li>
        <li><a href="<?= page_path('classes-inheritance') ?>">کلاس : وراثت</a></li>
        <li><a href="<?= page_path('classes-visibility') ?>">کلاس : ‌Visibility</a></li>
        <li><a href="<?= page_path('classes-constructor') ?>">کلاس : سازنده ها</a></li>
        <li><a href="<?= page_path('static') ?>">ثابت ها</a></li>
        <li><a href="<?= page_path('interfaces') ?>">اینترفیس ها</a></li>
        <li><a href="<?= page_path('abstract') ?>">کلاس های ابسترکت</a></li>
        <li><a href="<?= page_path('exceptions') ?>">اکسپشن ها</a></li>
    </ol>
    <a href="<?= page_path('credits') ?>">حمایت</a>
</div>
