<?php partial('header', ['title' => 'PHP Apprentice']) ?>

<div class="container small center">
    <div>
        <div class="home-title-wrapper">
            <div class="home-logo"><?= icon('elephant') ?></div>
            <h1 class="home-title">شاگرد پی اچ پی</h1>
            <h3 class="home-subtitle">یک کتاب آنلاین برای یادگیری پی اچ پی</h3>
        </div>
        <p>
            PHP Apprentice is an online, open source book about the PHP programming language. PHP is one of the most popular platforms for building websites and web services. It is a great language that is easy to learn and allows you to build powerful and complex web applications very quickly.
        </p>
        <p>
            The goal of PHP Apprentice is to be an easy to understand resource for learning how to write good code in PHP. There are a lot of PHP tutorials on the internet that use outdated practices or insecure code. I want this book to show how to write PHP code with quality.
        </p>
        <p>
            The contents of PHP Apprentice are for beginners and experienced PHP developers. The book currently has content for learning the basics of the language. In the future, more pages will be added for more advanced topics like building websites, database integration and security.
        </p>
        <p>
            PHP Apprentice is currently a work in progress. If you would like to give feedback or request a certain discussion topic, check out the <a href="https://github.com/restoreddev/phpapprentice" target="_blank">GitHub repository</a>.
        </p>
        <div class="home-buttons">
            <a href="<?= page_path('basics') ?>" class="button">
                <div class="icon"><?= icon('book-reference') ?></div>
                شروع فصل اول
            </a>
            <?php partial('menu_button') ?>
        </div>
        <hr />
        <p class="firstCrt">Created and managed by <a href="https://twitter.com/restoreddev" target="_blank">Andrew Davis @restoreddev</a>
        <p class="firstCrt">translate to Persian by <a href="https://twitter.com/restoreddev" target="_blank">Reza Farokhi Pour @rezafarokhii</a>
        <p class="persianCrt"> ترجمه به فارسی توسط:<a href="https://twitter.com/rezafarokhii" target="_blank"> رضا فرخی پور </a>
    </div>
</div>

<?php partial('menu_modal') ?>
<?php partial('footer') ?>
