<?php partial('header', ['title' => 'شاگرد پی اچ پی']) ?>

<div class="container small center">
    <div>
        <div class="home-title-wrapper">
            <div class="home-logo"><?= icon('elephant') ?></div>
            <h1 class="home-title">شاگرد پی اچ پی</h1>
            <h3 class="home-subtitle">یک کتاب آنلاین برای یادگیری پی اچ پی</h3>
        </div>
        <p>
            شاگرد پی اچ پی یک کتاب آنلاین, اپن سورس درباره ی زبان برنامه نویسی پی اچ پی می باشد. پی اچ پی یکی از محبوب ترین پلتفرم ها برای ساخت وبسایت ها و وب سرویس ها می باشد. پی اچ پی یک زبان بزرگ است که یادگیری آن بسیار ساده می باشد و به شما اجازه می دهد که وب اپلیکیشن های قدرتمند و پیچیده را به سادگی ایجاد کنید
        </p>
        <p>
            هدف این کتاب این است که یک منبع قابل فهم برای یادگیری و کدنویسی برای پی اچ پی باشد. آموزش های زیادی از پی اچ بر روی سطح اینترنت وجود دارد که از شویه های قدیمی و کدهای نا امن استفاده می کنند. هدف من این است که این کتاب به شما نشان دهد چگونه در پی اچ پی کد با کیفیت بنویسید
        </p>
        <p>
            محتوای این کتاب برای مبتدیان و برنامه نویسان حرفه ای می باشد. این کتاب در حال حاضر حاوی محتوایی برای یادگیری اصول اولیه زبان برنامه نویسی پی اچ پی می باشد. در آینده صفحات بیشتری برای قسمت های پیشرفته مانند ساخت وبسایت, کار با دیتابیس و امنیت اضافه خواهد شد
        </p>
        <p>
            این کتاب در حال توسعه می باشد, اگر مایل هستید بازخورد خودتان برای ما ارسال کنید یا در مورد یک موضوع مشخص صحبت کنید, می توانید از این لینک استفاده کنید <a href="https://github.com/restoreddev/phpapprentice" target="_blank">مخزن گیت هاب</a>
        </p>

        <div class="home-buttons">
            <a href="<?= page_path('basics') ?>" class="button">
                شروع فصل اول
                <div class="icon"><?= icon('book-reference') ?></div>
            </a>
            <?php partial('menu_button') ?>
        </div>
        <hr />
        <p class="firstCrt">Created and managed by <a href="https://twitter.com/restoreddev" target="_blank">Andrew Davis @restoreddev</a>
        <p class="firstCrt">translate to Farsi by <a href="https://twitter.com/restoreddev" target="_blank">Reza Farokhi Pour @rezafarokhii</a>
        <p class="persianCrt"> ترجمه به فارسی توسط:<a href="https://twitter.com/rezafarokhii" target="_blank"> رضا فرخی پور </a>
    </div>
</div>

<?php partial('menu_modal') ?>
<?php partial('footer') ?>
